# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: HyG
brief-intro: Front-end Dev Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gaohaoyang.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username:
facebook_username:
github_username:  Gaohaoyang
email: gaohaoyang126@126.com
weibo_username: 3115521wh
zhihu_username: gaohaoyang

description_footer: 这里记录我前端之旅的沿途风景，一路牛逼！


# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

category_dir: category/
tag_dir: tag/

#excerpt
excerpt_separator: "\n\n\n\n"

#paginate
gems: [jekyll-paginate]
paginate: 5

#comments
#two ways to comment, only choose one, and use your own short name
#两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: hygblog
disqus_shortname: #gaohaoyang
