# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cайт нашего дома
brief-intro: г. Москва, ул. Новомарьинская д. 32
baseurl: ""
url: "https://super-dom.github.io"

permalink: /:year/:month/:day/:title/

# other links
twitter_username:
facebook_username: 
github_uri: super-dom/super-dom.github.io
email: 
linkedIn_username: 
dribbble_username:

description_footer: 

# comments
# two ways to comment, only choose one, and use your own short name
# duoshuo_shortname: #hygblog
# disqus_shortname: gaohaoyang

# statistic analysis
# google_analytics_id: UA-72449510-4 # google analytics tracking id 

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 10

plugins:
  - jekyll-paginate
